### ISSUE TITLE
Sauvegarde impossible des commentaires

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#118]
En mode éditeur, dans la partie commentaire, il peut arriver que lorsqu'on sauvegarde un commentaire, celui-ci ou sa mise en forme disparaisse lorsque l'on change d'onglet et que l'on revient dessus, toujours en mode éditeur. Ca ne semble être qu'un problème ponctuel, puisque je l'ai rencontré pour le dossier 74, mais pas pour le dossier 58.

**Comment by algaudin** [comment]
Pour apporter quelques précisions, la difficulté de sauvegarde et de validation est valable en mode "Professeur", étant donné que la validation pour les étudiants, si j'ai bien compris, ne leur est pas possible. 
Généralement, en cliquant sur "Sauvergarder tous les commentaires", le contenu s'efface si l'on a pas préalablement "Validé" le commentaire. Parfois, même validé, le commentaire n'apparait pas en mode "Visualisation" du dossier, même après rechargement de la page.

**Comment by MrGecko** [comment]
Je vais tâcher de reproduire les problèmes de mon côté.
