### ISSUE TITLE
Problème lors de la réinsertion des notes dans la traduction affichée

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-app#119]
Souhaité : https://dev.chartes.psl.eu/adele/documents/74/edit/translation
Affiché :  https://dev.chartes.psl.eu/adele/documents/74/view/transcription    (ne sélectionner que la traduction)

Résultat retourné par l'api: https://dev.chartes.psl.eu/adele/api/1.0/documents/74/view/translations

Problèmes rencontrés :  
- [ ] l'enrichissement typo est dans des <hi rend="..."></hi> et n'est pas stylé (css)
- [ ] les notes ne sont pas correctement positionnées (problème de pointeurs)
- [ ] certains mots sont collés alors qu'ils ne le devraient pas (probablement un effet du point précédent)
- [ ] seing >seing.  (toujours le même problème de pointeur)

**Comment by MrGecko** [comment]
NB: problème niveau API

**Comment by algaudin** [comment]
Le décalage que l'on observe pour les notes dans la traduction existe aussi pour les parties du discours, où les zones affichées débutent avant la zone effectivement sélectionnée en mode éditeur.
