### ISSUE TITLE
Sélection du premier mot dans "Parties du discours"

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#123]
Sauf mauvaise manipulation de ma part, je n'arrive pas attribuer une partie du discours pour une zone sélectionnée débutant au premier mot de la transcription. J'ai essayé de multiples manières, en double cliquant sur le mot, en commençant la sélection par le dernier mot de la zone, mais cela ne fonctionne pas.

**Comment by MrGecko** [comment]
Oui le bug est connu.
