### ISSUE TITLE
Passage d'un dossier à un autre

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#125]
Lorsque l'on se trouve dans un dossier, il y a, au dessus du titre "← Dossier 34" et "Dossier 35 →", qui permettent de passer au dossier précédent ou au dossier suivant. 
Que l'on soit dans n'importe quel dossier, les numéros de ces deux dossiers ne changent pas, et les liens ne semblent pas être effectifs

**Comment by MrGecko** [comment]
En effet, ces liens qui devraient faciliter la navigation entre dossiers sont encore factices.
