### ISSUE TITLE
Repérage des caractères externes sur le facsimilé

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#129]
Dans la version de Thélème, les caractères externes étaient parfois directement visible sur le facsimilé, avec des zones entourées de rouges et des notes qui apparaissaient lorsque l'on survolait le facsimilé. Est-ce prévu dans Adele ?

**Comment by MrGecko** [comment]
Oui il est prévu deux couches d'annotations : une spécifique à l'alignement de l'image avec la transcription et une seconde plus libre.

**Comment by algaudin** [comment]
Très bien ! Merci pour la réponse :)
