### ISSUE TITLE
Choix des couleurs dans la visualisation des parties du document

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#130]
En mode consultation des dossiers, le surlignage des parties du discours rend parfois difficile la lecture du contenu de la partie (par exemple, la date de temps en marron, et le texte est de couleur noire ou grise).

**Comment by MrGecko** [comment]
En effet, cela a déjà été retravaillé par la personne en charge de l'intégration graphique du site et il faudrait que je vérifie pourquoi cela n'est pas encore installé.
