### ISSUE TITLE
Bug dans l'affichage de la transcription dans "Parties du discours"

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#136]
Après avoir fait le repérage des abréviations dans la partie "Transcription", et au passage dans la partie du discours, il y a parfois des bouts de "x>" ou simplement ">" qui apparaissent (notamment dans le dossier 24). 
![image](https://user-images.githubusercontent.com/33345655/88540855-0a5cd200-d014-11ea-9250-9b5e923b6717.png)

J'ai essayé en supprimant le repérage des abréviations et en le réintroduisant, mais le problème se reproduit.

**Comment by MrGecko** [comment]
Oui, c'est notre problème principal aujourd'hui, plusieurs autres issues y font déjà référence directement ou indirectement.
