### ISSUE TITLE
Affichage de l'image dans le dossier 144

### ISSUE THREAD

**Issue by algaudin** [chartes/adele-app#140]
L'image du manuscrit dans le dossier 144 n'est pas complète. Il semble manquer une partie à droite. Pensant qu'il s'agissait probablement d'un problème de chargement de l'image, j'ai rechargé à plusieurs reprises la page, mais rien ne change.

**Comment by MrGecko** [comment]
Il s'agit bien de la seule version dont nous disposons actuellement : [https://iiif.chartes.psl.eu/images/adele/CCI/AE_II_84.jpg/full/full/0/default.jpg](url). Il faudrait donc chercher à la source s'il en existe une version plus complète numérisée.

**Comment by algaudin** [comment]
Il existe une version complète numérisée, disponible sur Wikimedia : [https://commons.wikimedia.org/wiki/File:Hugues_Capet_988_charte_Maisons_Alfort.jpg](url)  , mais on ne peut pas tellement zoomer dessus pour lire ce qui est écrit. 
Sinon, l'image en bonne qualité est mise à disposition sur la base Archim des Archives Nationales  : [http://www2.culture.gouv.fr/Wave/image/archim/0013/dafanch06_s200005n00005_2.jpg](url)

**Comment by MrGecko** [comment]
J'ai mis à jour l'image. 
Aussi, la visionneuse permet désormais de zoomer plus loin. 
Problème : si on zoom trop loin l'image disparaît et il faut revenir en arrière pour la faire réapparaître.

Cela devrait être résolu le jour où on changera de visionneuse.
