### ISSUE TITLE
Ne pas montrer le facsimilé si le document n'est pas lié à un manifeste

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-app#16]
Que ce soit en **mode consultation** ou en **mode édition**, il ne faut pas montrer le facsimilé quand le document n'a pas de manifeste lié (le cas est envisageable).

**Comment by MrGecko** [comment]
NB: c'est déjà implémenté pour le mode consultation. Penser à réutiliser l'icone fontawesome pour le mode édition ?

**Comment by morganlegal** [comment]
Tu peux me donner un numéro de dossier qui n'a pas de manifeste ? Merci
