### ISSUE TITLE
Le bouton pour changer d'utilisateur en mode édition n'apparaît pas

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-app#19]
1) Créer un nouveau document
2) Lier une liste d'utilisateur au document
3) Ajouter une transcription en tant que professeur
4) Se déconnecter puis se connecter en tant qu'élève
5) Ajouter une transcription
6) Se connecter en tant que professeur

Le bouton changer d'utilisateur n'apparaît pas. Il apparaît cependant en mode Admin

**Comment by morganlegal** [comment]
je pense que c'est résolu

**Comment by MrGecko** [comment]
@morganlegal 
Quand on ajoute un document sans manifeste lié et qu'on se connecte sur la page d'édition :
`Uncaught (in promise) TypeError: Cannot read property 'fragments' of undefined`
Dans la méthode fetchFragments ligne 76
