### ISSUE TITLE
Disparition transcription

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#28]
Dans dossier 20, après sauvegarde de modifications dans l'onglet parties du discours, la transcription Professeur a disparu (remplacée par celle du compte Pierre Pocard).

**Comment by PierrePocard** [comment]
Idem pour dossier 22. Avec apparition d'un message d'erreur.

**Comment by PierrePocard** [comment]
Après mise à jour de la base, le problème ne semble plus se poser.

**Comment by MrGecko** [comment]
La base rechargée était encore en lecture seule.
