### ISSUE TITLE
Enregistrement modifications notice

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#29]
Dans l'onglet notice, après avoir cliqué sur bouton "enregistrer les modifications", devient bouton "erreur".

**Comment by MrGecko** [comment]
Je pense avoir résolu le problème, merci de confirmer et de fermer le ticket le cas échéant.

**Comment by PierrePocard** [comment]
Effectivement, ça marche.

**Comment by PierrePocard** [comment]
@MrGecko Le problème est réapparu.

**Comment by PierrePocard** [comment]
@MrGecko  
Dans dossier nouvellement créé (111), impossible d'enregistrer les modifications de la notice.

**Comment by MrGecko** [comment]
@PierrePocard peux-tu restester cette fonctionnalité et nous donner le plus de détails possible en cas d'erreur ?

**Comment by PierrePocard** [comment]
@MrGecko 
J'étais justement en train de le faire.
Le bug ne se présente que sur certains dossiers. Je les passe tous en revue et je reviens vers toi.

**Comment by PierrePocard** [comment]
@MrGecko 
Appuyer sur le bouton "enregistrer les modifications" n'a aucun effet dans les dossiers suivants : 32 35 59 61 62 63 64 65 72 79 82 85 88 89 90 91 92 93 94 109 112.
Pour les autres dossiers, la fonctionnalité d'enregistrement fonctionne normalement.

**Comment by MrGecko** [comment]
Résolu avec le dernier patch: le problème se produisait lorsque le document n'était pas rattaché à une institution
