### ISSUE TITLE
Saisie transcription

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#33]
En mode édition, les indications de changement de ligne ne sont pas enregistrées. Certaines lettres non plus.

**Comment by MrGecko** [comment]
Peux-tu fournir un exemple pour reproduire ce comportement s'il-te-plaît ?

**Comment by PierrePocard** [comment]
Dans le dossier 111 que je viens de créer (Acte de Paio Peres Romeu), je n'arrive pas à  distinguer deux segments dans la transcription 1. [Testamentum Pellagio Petriz Romeu] 2. [In nomine Sancte et Individue Trinitatis.]

**Comment by PierrePocard** [comment]
http://dev.chartes.psl.eu/adele/documents/111/edition

**Comment by MrGecko** [comment]
@PierrePocard : peux-tu tester à nouveau s'il-te-plaît ?
