### ISSUE TITLE
Problème avec les caractères &nbsp présents dans les textes

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-app#34]
Lors de l'enregistrement de transcriptions contenant des espaces insécables (&nbsp) la transcription est corrompue :
[http://dev.chartes.psl.eu/adele/documents/66/edition](http://dev.chartes.psl.eu/adele/documents/66/edition)  (données de Professeur1)

Cela advient même quand on ne modifie pas directement la transcription (par exemple lors des alignments facsimilé ou parties de discours). Connecté en tant qu'admin, j'ai affiché les données du Professeur 1 et j'ai voulu ajouter un alignement sur le facsimilé :

`XML Parsing Error: undefined entity Location: http://dev.chartes.psl.eu/adele/documents/66/edition Line Number 1, Column 525:<doc><p>De ista ora in antea, ego Ylisiarius de Salve, <segment></segment>filius de Stephana, a te Guilelma vicecomitissa <segment></segment>que fuist moller de Bernardo Aton, <segment></segment>tant quant tenras la sennoria del castel de la Arena, <segment></segment>et ad aquel eres que auras d’en Bernart Aton, <segment></segment>de qual tu es preinz, lo castel de Berniz <segment></segment>non vos tolrai ne vos en tolrai ipsas fortedas que hodie ibi sunt <segment></segment>ni adenant factas i erunt per nomen de castel**&nbsp**;; `

Cela arrive dans plusieurs documents.

**Comment by morganlegal** [comment]
Corrigé

**Comment by PierrePocard** [comment]
@morganlegal

**Comment by MrGecko** [comment]
Bonjour Pierre, je n'ai encore mis à jour l'application avec le correctif proposé par morgan.

**Comment by MrGecko** [comment]
@PierrePocard je pense qu'après la mise en ligne de la mise à jour le problème est résolu.
