### ISSUE TITLE
Ajout d'un commentaire 

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#40]
En mode édition, les boutons "créer un nouveau commentaire" ne fonctionnent pas.

**Comment by MrGecko** [comment]
@morganlegal Peux-tu me confirmer que la fonctionnalité d'édition/création de commentaire n'est pas implémentée ? 
L'interface est présente mais il n'y a pas de message d'erreur (ce qui en soit me réjouit :D).

**Comment by morganlegal** [comment]
@MrGecko oui c'est à cette étape que je me suis pour le moment arrêté
