### ISSUE TITLE
Commentaires parties du discours

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#43]
Dans l'onglet parties du discours en mode visualisation, les commentaires du champ contenu ne sont pas visibles.

**Comment by MrGecko** [comment]
@PierrePocard  Oui en effet, merci d'avoir ouvert ce ticket. La visualisation des notes n'est pas encore implémentée en mode visualisation. C'est une chose à faire.

**Comment by PierrePocard** [comment]
@MrGecko 
La visualisation des notes fonctionne très bien. En revanche, lorsqu'il n'y a pas de commentaire, sur une partie, une bulle indiquant "none" s'affiche (voir dans le document 113). Serait-il possible de la supprimer et de n'afficher de bulle que lorsqu'il y a effectivement un commentaire à afficher?
