### ISSUE TITLE
La transcription affichée est celle de l'ancien utilisateur sélectionné

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-app#45]
Lorsqu'on change d'utilisateur en mode édition pour un ayant une transcription existante puis qu'on change à nouveau mais pour un qui n'en a pas, la transcription reste affichée (et une éventuelle modification puis sauvegarde échouera avec cet utilisateur car il n'a effectivement pas de transcription en base).
Ex : avec le dossier 20
1. Je me connecte en tant qu'admin : je n'ai pas de transcription
2. Je change la vue pour celle de Professeur1 : la transcription de Prof1 apparaît
3. Je change la vue pour celle de Prof2 qui n'a pas de transcription (par exemple) : la transcription de Prof1 est toujours affichée.

**Comment by morganlegal** [comment]
Corrigé
