### ISSUE TITLE
Transcription altérée par modifications dans l'onglet parties du discours

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#49]
Après enregistrement de modifications dans l'onglet parties du discours, la transcription est corrompue dans l'onglet édition (cf. capture d'écran document 20 : la plupart du texte est considérée comme abrégée.)

![2018-10-18 2](https://user-images.githubusercontent.com/43371717/47162376-1c182e00-d2f4-11e8-95f7-4175887b4d79.png)

**Comment by MrGecko** [comment]
Merci pour ce ticket @PierrePocard. 
Je crois que la dernière version de la base de donnée du projet github/adele contient encore des décalages au niveau des pointeurs. Et comme la base a été restaurée depuis ce projet par mégarde après un crash serveur, le problème est réapparu. Je réglerai ça asap.

**Comment by PierrePocard** [comment]
@MrGecko 
C'est bien noté. En attendant, je ne touche pas aux parties du discours!

**Comment by MrGecko** [comment]
@PierrePocard peux-tu vérifier à nouveau ce comportement ?

**Comment by PierrePocard** [comment]
@MrGecko 
J'ai l'impression que ça fonctionne très bien. L'enregistrement des parties du discours se fait correctement, et ne modifie plus l'édition. L'affichage en mode visualisation correspond à ce qui est enregistré.
