### ISSUE TITLE
Affichage des parties du discours après enregistrement

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#50]
Après segmentation des parties du discours et enregistrement des modifications, changer d'onglet puis revenir à l'onglet parties du discours, ou recharger la page : la segmentation affichée ne correspond pas à ce qui a été enregistré. 
Plusieurs cas de figure observés: 
 - un seul type de partie affiché pour tout le document.
 - plusieurs parties affichées mais des décalages entre la segmentation affichée et la segmentation définie avant enregistrement
 - plusieurs parties affichées mais pas toutes celles enregistrées.

**Comment by MrGecko** [comment]
Les issues #49, #50 #51 proviennent probablement du même problème de données en base; cf mon commentaire sur #49

**Comment by morganlegal** [comment]
A priori le problème venait plutôt de moi
