### ISSUE TITLE
Affichage transcription sans traduction

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#52]
@architexte 
Pour les documents qui ont une transcription mais pas encore de traduction ou ceux qui ne nécessitent pas de traduction, serait-il possible, en mode visualisation, d'afficher par défaut seulement la transcription et pas les deux onglets traduction/transcription? Cela permettrait de ne pas avoir à désactiver la vue de la traduction et de voir directement l'édition. Actuellement, les deux onglets sont affichés mais la transcription n'apparaît pas (cf. doc 26), et il faut désactiver l'affichage de la traduction pour la voir. On peut donc avoir l'impression d'un bug ou d'une absence de transcription, ce qui n'est pas le cas.

**Comment by MrGecko** [comment]
bien vu

**Comment by PierrePocard** [comment]
@MrGecko
Aucune transcription ne s'affiche pour les documents concernés (23 31 40 50 62 73 75 77 79).
