### ISSUE TITLE
Rendre toujours visible les boutons d'enrichissement du texte pendant la saisie d'une transcription

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#56]
En mode édition, au fil de la transcription/ traduction, avec l'allongement de la page, les boutons de structure éditoriale et d'enrichissements sémantiques et typographiques ne sont plus visibles et il faut faire des aller-retours entre le haut et le bas de la page avec la barre de défilement.
Il serait plus commode que ces boutons soit toujours visibles pendant la saisie.

**Comment by morganlegal** [comment]
J'ai limité la hauteur de l'éditeur à 80% de la hauteur utile du navigateur. Ca doit régler le problème
