### ISSUE TITLE
Bouton ¶ en mode édition

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#57]
Lors de la saisie d'une transcription ou d'une traduction, appuyer sur le bouton ¶ n'a aucun effet apparent (j'ignore d'ailleurs à quoi le bouton doit servir).

**Comment by morganlegal** [comment]
Il s'agit du bouton paragraphe. Il n'est utile que quand on a défini un bloc de texte coimme étant un vers et qu'on veut le retransformer en paragraphe
