### ISSUE TITLE
Pas de bouton changer d'utilisateur dans les nouveaux dossiers

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#58]
Dans les dossiers nouvellement créés (112 et 113), le bouton changer d'utilisateur n'apparaît pas.

**Comment by MrGecko** [comment]
C'est parce qu'ils n'ont pas de liste d'utilisateurs. 
Tu peux aller dans le tableau de bord > mes utilisateurs   pour associer une liste à un document
