### ISSUE TITLE
Transcription altérée 

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#59]
@MrGecko 
Lors de la saisie d'une nouvelle transcription, les abréviations et l'ajout de pointeurs ne sont pas enregistrés, ou mal enregistrés (coupures de mots/ décalages/ extension des abréviations à l'ensemble du texte).

Peut-être même problème que #49 #50 #51.

**Comment by PierrePocard** [comment]
@MrGecko 
Pour que l'enregistrement d'une transcription se fasse correctement, il faut procéder par couches successives, en saisissant le texte, puis les abréviations, avant d'ajouter les pointeurs et les notes. Saisir tous ces éléments altère la transcription.

**Comment by PierrePocard** [comment]
@MrGecko 
Dans le document 47, après enregistrement de modifications des pointeurs dans la transcription, celle-ci a semble-t-il disparu.
![image](https://user-images.githubusercontent.com/43371717/49017018-08c87000-f188-11e8-93bc-21462dc3bd88.png)

**Comment by MrGecko** [comment]
le problème des <br> est résolu
