### ISSUE TITLE
Permettre de passer du mode édition au mode visualisation

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#60]
De même que l'on peut passer de la visualisation à l'édition avec le bouton "éditer", un bouton "visualiser" en mode édition pourrait être pratique pour éviter de devoir passer par http://dev.chartes.psl.eu/adele/documents .

**Comment by MrGecko** [comment]
Très bonne suggestion

**Comment by MrGecko** [comment]
Pour proposer ce changement de page à l'utilisateur il faut résoudre le cas où il y a des modifications en cours mais non enregistrées en mode édition.

Deux cas possibles : 
- popup pour demander  "sauvegarder ou annuler"
ou
- page de consultation ouverte dans un nouvel onglet
