### ISSUE TITLE
Enregistrement des notes

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#63]
@MrGecko 

 - Créer une nouvelle note dans la transcription et valider. 
 -  Si on veut lier le texte correspondant dans la traduction à la note créée : une liste de notes apparaît, mais on ne voit pas leur contenu. Il est impossible de valider 
![2018-10-26](https://user-images.githubusercontent.com/43371717/47565675-9dda0e00-d929-11e8-823f-f9f3434e4171.png)

Sauvegarder les modifications puis recharger la page : la liste de notes n'apparaît plus.
![2018-10-26 1](https://user-images.githubusercontent.com/43371717/47565800-e98cb780-d929-11e8-9348-c2f6337f311c.png)

**Comment by MrGecko** [comment]
@PierrePocard : nous étions en train de régler quelques problèmes sur les notes de traduction/transcription cet après-midi. 
Je pense que cela fonctionne mieux désormais (mis à part la fonctionnalité "lier à une note existante" qui n'est pas toujours disponible).

Merci de tester à nouveau.

**Comment by PierrePocard** [comment]
@MrGecko Merci beaucoup!
Effectivement, il est possible d'ajouter des nouvelles notes et l'enregistrement fonctionne.
Les notes n'apparaissent cependant pas encore en mode visualisation. J'imagine que cela doit venir plus tard.

**Comment by MrGecko** [comment]
En effet il y a un ticket d'ouvert à ce sujet
