### ISSUE TITLE
Enregistrement notes liées

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#72]
@MrGecko 
- Lier un passage du texte à une note existante et valider. la note liée s'affiche.
- sauvegarder les changements.
- recharger la page : la note n'a pas été enregistrée.

**Comment by MrGecko** [comment]
@PierrePocard : je n'arrive pas à reproduire ce bug, peux-tu nous faire une série de capture d'écrans s'il-te-plaît ?

**Comment by PierrePocard** [comment]
@MrGecko 
Dans le document 113
-  je veux lier "Percy" dans la traduction à la note d'identification du lieu qui existe déjà dans la transcription.
![2018-11-15 4](https://user-images.githubusercontent.com/43371717/48543156-388e9280-e8c1-11e8-883c-34ff5feaedba.png)
- Je lie à la note déjà existante
![2018-11-15 1](https://user-images.githubusercontent.com/43371717/48543219-5f4cc900-e8c1-11e8-9237-4f265fbfd91a.png)
- Après validation, la note liée est bien présente
![2018-11-15 3](https://user-images.githubusercontent.com/43371717/48543287-7a1f3d80-e8c1-11e8-8790-7a69f9ad4e7c.png)
- Je sauvegarde les modifications puis recharge la page : la note liée n'est plus là (donc retour à la situation avant tentative de modification)
![2018-11-15](https://user-images.githubusercontent.com/43371717/48543422-c8ccd780-e8c1-11e8-9272-dd130b0a7159.png)

Le comportement est le même dans le cas de deux notes liées dans la transcription.

**Comment by PierrePocard** [comment]
Le comportement est le même dans d'autres documents.
