### ISSUE TITLE
Les notes créées dans la traduction n'apparaissent pas dans la liste des notes du document

### ISSUE THREAD

**Issue by morganlegal** [chartes/adele-app#76]
Lorsqu'on crée une note dans la traduction, elle est sauvée en base.
En revanche, elle n'apparait pas dans la liste des notes du document pour un utilisateur : `/adele/api/1.0/documents/20/notes/from-user/4`
J'ai l'impression que tu renvoies que les notes qui sont effectivement liées soit à la traduction soit à la transcription. Il en résulte que si tu crées une note puis la délies, si tu veux finalement la remettre tu es obligé de la récréer. Ca fait un doublon dans la base

**Comment by MrGecko** [comment]
Le truc c'est que si on la délie, elle n'est plus associée à ce document en particulier.
Du coup si on veut toujours la proposer dans la liste, il faudra aussi proposer toutes les notes de tous les documents de l'utilisateur...

**Comment by MrGecko** [comment]
fixed by [9fcecdd](https://github.com/chartes/adele-app/commit/9fcecddef42e8ea02b799ae6d4f62c2ea02cff01)
