### ISSUE TITLE
Enregistrement des notes

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#77]
Dans le document 120 : après saisie et enregistrement de nombreuses notes, une bonne partie du texte est enregistrée comme renvoyant à une seule et même note et bon nombre de notes n'apparaissent pas.
![image](https://user-images.githubusercontent.com/43371717/48777691-995c0780-ecd3-11e8-8a4f-7e91d3dbe900.png)

**Comment by PierrePocard** [comment]
Même problème pour le document 119.

**Comment by MrGecko** [comment]
À reproduire ensemble
