### ISSUE TITLE
Affichage dans l'onglet commentaire

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#79]
@MrGecko 
En mode visualisation, un message d'erreur s'affiche dans l'onglet commentaire, alors qu'aucun problème n'est apparent dans le mode édition

![image](https://user-images.githubusercontent.com/43371717/48783816-9c5df480-ece1-11e8-88cb-7acb7d7f2599.png)

**Comment by MrGecko** [comment]
Problème réglé.
Le problème était le même que pour les transcriptions/traductions :   les balises <br> (non auto-fermantes) faisaient planter le parseur XML car ce dernier attendant une balise fermante identique.

Il faudra néanmoins resaisir les commentaires corrompus (à voir ensemble)
