### ISSUE TITLE
Délimitation des zones du texte dans le fac-simile

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#80]
@MrGecko 
Dans l'onglet fac-simile du document 20
-modifier des zones de texte dans leaflet (par ex, supprimer une zone)
- appuyer sur le bouton "sauvegarder les zones de la page en cours" 
leaflet est rechargé à l'état antérieur aux modifications.

**Comment by PierrePocard** [comment]
@MrGecko 
Hors du document 20, les zones ne s'affichent pas dans leaflet en mode édition.
Le bouton "sauvegarder les zones de la page en cours"  produit le même effet : rechargement de leaflet à l'état antérieur.

**Comment by MrGecko** [comment]
À reproduire ensemble

**Comment by PierrePocard** [comment]
@MrGecko 
En fait c'est un problème de droits. Je ne peux pas modifier les données du compte Professeur1. #92
