### ISSUE TITLE
Impossible d'ajouter une transcription à certains documents

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#84]
@MrGecko 
Dans certains dossiers où aucune transcription n'existe (58-59-80-84-85-86-87-88-89-90-91-92-93-94), le bouton "ajouter une transcription" ne fonctionne pas.

**Comment by MrGecko** [comment]
@PierrePocard à revérifer

**Comment by PierrePocard** [comment]
@MrGecko 
C'est réglé!
