### ISSUE TITLE
Corruption de la transcription/traduction par l'ajout de notes

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#85]
@MrGecko 
Après enregistrement, les notes apparaissent souvent en décalé par rapport au texte correspondant (voir aussi #77)
![image](https://user-images.githubusercontent.com/43371717/48846185-bad5f580-ed9e-11e8-8ddf-750c0e2ec1da.png)

Ce décalage semble avoir une incidence sur les pointeurs en mode visualisation : on trouve au niveau des notes  des décalages/des césures qui ne correspondent pas à ce qui apparaît en mode édition.
![image](https://user-images.githubusercontent.com/43371717/48846319-20c27d00-ed9f-11e8-9c96-071f34d1fba7.png)

**Comment by MrGecko** [comment]
En effet, je constate le bug lorsqu'on crée une note qui commence juste après le début d'un segment d'alignement.
Si on se place au moins 1 caractère après le début d'un segment d'alignement, le problème ne se produit pas.
