### ISSUE TITLE
Enregistrement des commentaires

### ISSUE THREAD

**Issue by PierrePocard** [chartes/adele-app#86]
@MrGecko 
Après enregistrement, les commentaires n'apparaissent ni en mode visualisation ni en mode édition. Si on ajoute un commentaire ensuite, les commentaires précédemment enregistrés réapparaissent.

**Comment by MrGecko** [comment]
@PierrePocard je pense que ceci est arrivé sur un document que tu n'as pas crée toi-même. Par conséquent ta version n'est pas celle de référence et n'est pas affichée en mode visualisation.
Je n'arrive pas à le reproduire en mode édition (le commentaire s'affiche toujours même en rechargeant la page).
Aussi, je vois qu'actuellement il faut sauvegarder un à un les types de commentaires. Cliquer sur enregistrer ne sauvegarde que l'onglet courant

**Comment by PierrePocard** [comment]
@MrGecko 
Effectivement cela n'arrive que pour les documents que je n'ai pas créés. 
En mode édition, je peux créer un commentaire en affichant la version d'un autre utilisateur mais l'enregistrement ne se fait pas (même si aucun message d'erreur ne s'affiche).
En revanche si je modifie le commentaire déjà existant d'un autre utilisateur, il y a un message d'erreur au moment de l'enregistrement.
